openapi: 3.1.0
info:
  title: Scoutnet API
  summary: >-
    Scoutnet is the member management system for the Guides and Scouts of
    Sweden.
  description: |
    Scoutnet is the member management system for the Guides and Scouts of
    Sweden. This API provides access to various resources related to projects,
    groups, and participants.
  version: 0.3.7
  license:
    name: MIT
    identifier: MIT
  contact:
    name: Scoutnet
    url: https://github.com/Scouterna/scoutnet-api
tags:
  - name: project
    description: Endpoints related to "arrangemang"
  - name: global
    description: Endpoints that do not belong to a specific type of resource
servers:
  - url: https://s1.test.custard.no/api
    description: Test server
  - url: https://scoutnet.se/api
    description: Production server
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: |
        Use the ID of the resource you're accessing as username and the
        corresponding API key as password.
security:
  - basicAuth: []
paths:
  /body_key_list:
    $ref: ./paths/body_key_list.yaml
  /project/get/groups:
    $ref: ./paths/project_get_groups.yaml
  /project/get/participants:
    $ref: ./paths/project_get_participants.yaml
  /project/checkin:
    $ref: ./paths/project_checkin.yaml
  /project/get/questions:
    $ref: ./paths/project_questions.yaml
